const data = {
    products: [
        {
            name: 'Nike Slim Shirt',
            slug: 'nike-slim-shirt',
            category : 'Shirts',
            image : '/images/imagen1.webp',
            price : 120,
            countInStock : 10,
            brand : 'Nike',
            rating : 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Air Jordan 1 High OG "Royal Reimagined"',
            slug: 'air-jordan-1-high-og-"royal-reimagined"',
            category : 'Shoes',
            image : '/images/imagen2.jpeg',
            price : 180,
            countInStock : 10,
            brand : 'Nike',
            rating : 5.0,
            numReviews: 10,
            description: 'high quality shoes',
        },
        {
            name: 'Air Jordan 1 Low G NRG',
            slug: 'air-jordan-1-low-g-nrg',
            category : 'Shoes',
            image : '/images/imagen3.jpeg',
            price : 170,
            countInStock : 10,
            brand : 'Nike',
            rating : 0.0,
            numReviews: 10,
            description: 'high quality shoes',
        },
        {
            name: 'Nike TechKnit',
            slug: 'nike-techKnit',
            category : 'Shirts',
            image : '/images/imagen4.jpeg',
            price : 90,
            countInStock : 10,
            brand : 'Nike',
            rating : 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nike Sportswear Phoenix Fleece',
            slug: 'nike-sportswear-phoenix-fleece',
            category : 'Shirt',
            image : '/images/imagen5.webp',
            price : 80,
            countInStock : 10,
            brand : 'Nike',
            rating : 5.0,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nike Structure 25',
            slug: 'nike-structure-25',
            category : 'Shoes',
            image : '/images/imagen6.webp',
            price : 140,
            countInStock : 10,
            brand : 'Nike',
            rating : 0.0,
            numReviews: 10,
            description: 'high quality shoes',
        },
        {
            name: 'Nike Club Fleece Set',
            slug: 'nike-club-fleece-set',
            category : 'Shirt',
            image : '/images/imagen7.jpeg',
            price : 60,
            countInStock : 10,
            brand : 'Nike',
            rating : 0.0,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nike Dunk Low',
            slug: 'nike-dunk-low',
            category : 'Shoes',
            image : '/images/imagen8.webp',
            price : 55,
            countInStock : 10,
            brand : 'Nike',
            rating : 5.0,
            numReviews: 10,
            description: 'high quality shoes',
        },
    ],
};

export default data;